/**
 * On-demand loader and minimal typings for the YouTube IFrame Player API.
 *
 * Why the full API instead of a bare `<iframe>`: it lets us listen for the
 * `ENDED` state and restart the clip ourselves, so a finished sign loops
 * reliably and the player never navigates away — which a plain embed's `loop`
 * parameter does not guarantee across browsers.
 *
 * Privacy: the script is injected only when a visitor actually opens a video
 * (never while browsing the catalogue), and the player is created against the
 * `youtube-nocookie.com` host, so the privacy posture matches the old embed.
 */

export const YOUTUBE_NOCOOKIE_HOST = 'https://www.youtube-nocookie.com';

/** The slice of `YT.Player` this app uses. */
export interface YouTubePlayer {
  setPlaybackRate(rate: number): void;
  seekTo(seconds: number, allowSeekAhead: boolean): void;
  playVideo(): void;
  stopVideo(): void;
  getIframe(): HTMLIFrameElement;
  destroy(): void;
}

export interface YouTubePlayerEvent {
  target: YouTubePlayer;
  data: number;
}

interface YouTubePlayerOptions {
  host?: string;
  videoId: string;
  playerVars?: Record<string, string | number>;
  events?: {
    onReady?: (event: YouTubePlayerEvent) => void;
    onStateChange?: (event: YouTubePlayerEvent) => void;
  };
}

type YouTubePlayerConstructor = new (
  element: HTMLElement,
  options: YouTubePlayerOptions,
) => YouTubePlayer;

interface YouTubeApi {
  Player: YouTubePlayerConstructor;
  PlayerState: { ENDED: number; PLAYING: number; PAUSED: number };
}

declare global {
  interface Window {
    YT?: YouTubeApi;
    onYouTubeIframeAPIReady?: () => void;
  }
}

let apiPromise: Promise<YouTubeApi> | null = null;

/**
 * How long to wait for the API before giving up. A privacy extension or a
 * filtered network can drop the request without ever firing `error`, and an
 * unresolved promise leaves the dialog blank forever with nothing to act on.
 */
export const YOUTUBE_API_TIMEOUT_MS = 10_000;

/**
 * Loads the IFrame API once and resolves when `YT` is ready to use.
 *
 * Rejects — rather than hanging — when the script fails or takes too long, and
 * clears the cached promise on failure so a later attempt can retry instead of
 * inheriting a poisoned result. Callers are expected to offer the source's own
 * page as a fallback.
 */
export function loadYouTubeIframeApi(): Promise<YouTubeApi> {
  if (typeof window === 'undefined') {
    return Promise.reject(new Error('The YouTube IFrame API is browser-only'));
  }
  if (window.YT?.Player) return Promise.resolve(window.YT);

  apiPromise ??= new Promise<YouTubeApi>((resolve, reject) => {
    // Armed before anything can settle the promise; the callbacks below only
    // run once this synchronous block has finished.
    const timeoutId = setTimeout(() => {
      fail(`The YouTube IFrame API did not load within ${YOUTUBE_API_TIMEOUT_MS}ms`);
    }, YOUTUBE_API_TIMEOUT_MS);

    const settle = (run: () => void) => {
      clearTimeout(timeoutId);
      run();
    };

    const fail = (message: string) => {
      // Drop the cache so the next open starts a fresh attempt.
      apiPromise = null;
      settle(() => {
        reject(new Error(message));
      });
    };

    // Chain rather than overwrite: other callers may share the same global.
    const previous = window.onYouTubeIframeAPIReady;
    window.onYouTubeIframeAPIReady = () => {
      previous?.();
      if (window.YT?.Player) {
        const api = window.YT;
        settle(() => {
          resolve(api);
        });
      }
    };

    const script = document.createElement('script');
    script.src = 'https://www.youtube.com/iframe_api';
    script.async = true;
    script.addEventListener('error', () => {
      script.remove();
      fail('The YouTube IFrame API could not be loaded');
    });
    document.head.appendChild(script);
  });

  return apiPromise;
}

/**
 * Hosts a stored `videoUrl` may legitimately use. An explicit list, not a
 * suffix test: `endsWith('youtube.com')` also accepts `notyoutube.com`, which
 * would let a bad content entry embed a third party's player. The content is
 * generated by our own script, so the shapes are finite and known.
 */
const YOUTUBE_WATCH_HOSTS = new Set([
  'youtube.com',
  'www.youtube.com',
  'm.youtube.com',
  'youtube-nocookie.com',
  'www.youtube-nocookie.com',
]);

const YOUTUBE_SHORT_HOSTS = new Set(['youtu.be', 'www.youtu.be']);

/**
 * Extracts the video id from any YouTube URL shape the content uses. Returns
 * null rather than guessing, so a malformed entry simply does not play.
 */
export function youtubeId(url: string): string | null {
  try {
    const parsed = new URL(url);
    if (parsed.protocol !== 'https:') return null;
    if (YOUTUBE_SHORT_HOSTS.has(parsed.hostname)) return parsed.pathname.slice(1) || null;
    if (YOUTUBE_WATCH_HOSTS.has(parsed.hostname)) return parsed.searchParams.get('v');
    return null;
  } catch {
    return null;
  }
}
